apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: graphdb-single-vm-display
  annotations:
    autogenSpecType: SINGLE_VM
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: GraphDB deployment package on GCP
    source:
      repo: https://github.com/Ontotext-AD/gcp-deployment-package-graphdb.git
      sourceType: git
      dir: /
  ui:
    input:
      variables:
        allowed_ingress_cidrs:
          name: allowed_ingress_cidrs
          title: Allowed Ingress CIDRs
          section: networking
        boot_disk_size:
          name: disk_size
          title: Disk Size
          section: boot_disk
          xGoogleProperty:
            type: ET_GCE_DISK_SIZE
            gceDiskSize:
              diskTypeVariable: boot_disk_type
        boot_disk_type:
          name: boot_disk_type
          title: Boot Disk Type
          section: boot_disk
          xGoogleProperty:
            type: ET_GCE_DISK_TYPE
            zoneProperty: zone
        goog_cm_deployment_name:
          name: goog_cm_deployment_name
          title: Goog Cm Deployment Name
        machine_type:
          name: machine_type
          title: Machine Type
          xGoogleProperty:
            type: ET_GCE_MACHINE_TYPE
            zoneProperty: zone
        name:
          name: name
          title: Name
        network_interface:
          name: network_interface
          title: Network Interface
          section: networking
          xGoogleProperty:
            type: ET_GCE_NETWORK
            gceNetwork:
              allowSharedVpcs: true
              machineTypeVariable: machine_type
        project_id:
          name: project_id
          title: Project Id
        source_image:
          name: source_image
          title: Image version
          invisible: true
          xGoogleProperty:
            type: ET_GCE_DISK_IMAGE
        zone:
          name: zone
          title: Zone
          xGoogleProperty:
            type: ET_GCE_ZONE
      sections:
        - name: networking
          title: Networking
          tooltip: Networking related configurations
        - name: boot_disk
          title: Boot Disk
          tooltip: Configure the boot disk for GraphDB
